server:
 port: 8085
 
spring:
 application:
    name: catalog-service
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/inventory-management
    username: postgres
    password: root
    intialization-mode: always
 jpa:
   hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

springdoc:
  packagesToScan: com.otsi.retail.catalog-service
  

  
