server:
 port: 9092
 
spring:
 application:
    name: inventory-service
 datasource:
    platform: postgres
    url: jdbc:postgresql://10.100.50.115:5432/inventory-module
    username: postgres
    password: Otsi@123
  
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
 rabbitmq:
      host: aeb8cc91b2f7948a8bc858c8d8f7fb4d-768590259.ap-south-1.elb.amazonaws.com
      port: 5672
      username: user
      password: piV7lSjh6q
  
 httpclient:
	  pool:
		   type: fixed
		   max-connections: 10000
		   acquire-timeout: 800000
		   max-life-time: 3000s
		   max-idle-time: 600s
	  connect-timeout: 80000
	  response-timeout: 600s
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.100.143.45:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

logging:
    file:
      name: C:\Users\retails\Desktop\logs\inventory-module.log       
    level:
      com.otsi.retail.inventory.service: DEBUG   

   
