server:
 port: 9092
 
spring:
 application:
    name: inventory-service
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/inven-module
    username: postgres
    password: Vasavi
    initializaion.mode: always
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/inventory-module.log    
    level:
     com.otsi.retail.inventory.service: DEBUG   

springdoc:
    packagesToScan: com.otsi.retail.inventory
resilience4j:
  circuitbreaker:
    instances:
      newSale:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
