server:
 port: 9092
 
spring:
 application:
    name: barcode-module
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/barcode-module
    username: postgres
    password: Vasavi
    initializaion.mode: always
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   springdoc:
    packagesToScan: com.otsi.retail.barcode

